version: "3"
services:
  hub:
    image: selenium/hub:4.16
    ports:
      - 4444:4444
#      - 4442:4442
#      - 4443:4443
  chrome:
    image: selenium/node-chrome:4.16
    shm_size: '2g'  #browsers are heavy objects and required more memory tu run, ig memory not assigned it will crash
    depends_on:
      - hub
    deploy:
      replicas: 4
    environment:
      - SE_EVENT_BUS_HOST=hub   # to understand chrome container where hub is running i.e. communication between hub and chreome container
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.16
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 2
    environment:
      - SE_EVENT_BUS_HOST=hub   # to understand chrome container where hub is running i.e. communication between hub and chreome container
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443